double Mean(double*, int);
double Variance(double*, int);
double Mediane(double[], int);
double * ReadDataFromFile(const char*, int);
void Print(double *, int);
void Print(const char *, double *, int);
void SwapByValue(double, double);
void SwapByRef(double &, double &);
void SwapByPointer(double *, double*);
void SelectionSort(double *, int);